### ISSUE TITLE
Not being able to add Dropbox to rcs clone

### ISSUE THREAD

**Issue by vaibhavholani** [hbs-rcs/hbsgrid-docs#16]
I am using the instructions given here https://hbs-rcs.github.io/hbsgrid-docs/syncfiles.html and the drive just does not show up in the remotes section

**Comment by izahn** [comment]
Thank you for reporting this! I tried it out and found that newly configured remotes don't show up automatically, you have to click the "Refresh" button, like this:
![rclone](https://user-images.githubusercontent.com/321235/151354084-eefcc818-c8b9-465a-af23-117f012ae22c.gif)
Can you try it and let me know if that works for you?

**Comment by izahn** [comment]
Hmm, I just checked and your `~/.config/rclone/rclone.conf` file exists but is empty. Basically the config you see there in the terminal should be saved to that file, but it is not. I'll reach out over email to set up a time to look at this together.

**Comment by vaibhavholani** [comment]
Solved!

**Comment by izahn** [comment]
For future reference, the problem was that the config file couldn't be written to because the home directory disk quota had been reached. The solution was to delete files to get back under the quota.
