### ISSUE TITLE
Not being able to delete items from the trash

### ISSUE THREAD

**Issue by vaibhavholani** [hbs-rcs/hbsgrid-docs#18]
Title^
<img width="907" alt="Screenshot 2022-01-27 at 10 52 42 AM" src="https://user-images.githubusercontent.com/59990189/151394660-1968eaaa-228e-4f57-84b4-4e4e4488f621.png">

**Comment by vaibhavholani** [comment]
yeah, it seems like it is full.
<img width="724" alt="Screenshot 2022-01-27 at 11 25 28 AM" src="https://user-images.githubusercontent.com/59990189/151400625-401f4574-d931-4bfb-98b9-173be38a20e0.png">

**Comment by izahn** [comment]
Yep, you have used all 50 Gb, that is likely the cause of this and the other problems you reported. Bummer that trying to empty your trash didn't work, you were on the right track with that.

You should be able to open a Terminal on the Grid and run 
```
rm -rf ~/.local/share/Trash/*
```
to manually empty the trash, can you try that?

**Comment by vaibhavholani** [comment]
Done, however, I only freed up about 205MB on the machine and all my home folders are empty. Not sure what is taking up all the space.
<img width="725" alt="Screenshot 2022-01-27 at 11 43 51 AM" src="https://user-images.githubusercontent.com/59990189/151404285-2dcf5b85-2708-4d8b-86af-be42faf6ae75.png">

**Comment by izahn** [comment]
No, I think it looks good. The first number tells you how much space you are using, see how it went down from `51200M` to `205M`? I think you should be all set. Can you try e.g. configuring `rclone` again as in https://github.com/hbs-rcs/hbsgrid-docs/issues/16 and see if it works now?

**Comment by vaibhavholani** [comment]
It works now! Thanks!
