### ISSUE TITLE
Desktop UI seems to be reset

### ISSUE THREAD

**Issue by devbioinfoguy** [hbs-rcs/hbsgrid-docs#25]
When logging into NoMachine, I have icons on my desktop. After activating the Grid3-UI, the desktop icons are no longer displayed.

(I have not yet tried the TweaksUI tool to see if these are turned off)

**Comment by devbioinfoguy** [comment]
Interesting -- the settings showed "Show Icons" as "On". But didn't. I had to turn this setting off, then back on again, and they re-appeared.

**Comment by izahn** [comment]
Yeah, the desktop icons feature in Gnome was buggy and was removed in 2017. There is a blog post about it at https://csorianognome.wordpress.com/2017/12/21/nautilus-desktop-plans/ and more details at https://gitlab.gnome.org/GNOME/nautilus/-/issues/158

To be clear, desktop icons still exist in the version of Gnome we run on the Grid, but this feature is buggy and painful. The Gnome devs gave up on it, and so did I.

**Comment by devbioinfoguy** [comment]
Wow! That's tragic to hear.

**Comment by izahn** [comment]
Personally I feel 'meh" about it. Chrome OS doesn't have desktop icons at all, may be the way of the future.

**Comment by devbioinfoguy** [comment]
LOL! I love that you're so nonchalant about it.

**Comment by devbioinfoguy** [comment]
We will need to inform users of this UI problem. Or at least prepare Liz for an onslaught of tickets she may receive.

**Comment by izahn** [comment]
Of the 33 people who've used it since this became the default we've had 0 inquires.

**Comment by izahn** [comment]
Well, 1. Yours!
