### ISSUE TITLE
Consider using versioning

### ISSUE THREAD

**Issue by izahn** [hbs-rcs/hbsgrid-docs#26]
Should be easy enough to maintain multiple versions of the documentation: https://squidfunk.github.io/mkdocs-material/setup/setting-up-versioning

**Comment by devbioinfoguy** [comment]
Hmmm... This is good to know. But that then negates moving docs into the hbs.edu site, yes?

**Comment by izahn** [comment]
I'm thinking of moving hbs.edu docs here. And then moving here to hbs.edu :-)
