### ISSUE TITLE
Remove requests section and link out to sharepoint

### ISSUE THREAD

**Issue by paul-dibello** [hbs-rcs/hbsgrid-docs#30]
For the account requests and other support for the grid, I think it might be better to point to our current website.

**Comment by izahn** [comment]
I think this needs discussion. I really think having two separate documentation sites will be too confusing. To try to avoid that I've ported the current documentation here as version 2.5. That might not be the way we want to do it, I'd like to find a way that doesn't involve having two separate places for users to look for documentation.

**Comment by paul-dibello** [comment]
Sure, let's discuss.  Having information duplicated across two sites is not ideal.  It may be a function of deciding which site is appropriate for what information.

**Comment by izahn** [comment]
Maybe, but I don't really see any advantage in having two different sites, I'd really like to see them reconciled and consolidated into one.

**Comment by paul-dibello** [comment]
My understanding is that the docs you are doing are specific to the Grid 3.0 environment, not the entire grid.  Is that wrong?

**Comment by izahn** [comment]
Yes, my docs are for Grid 3.0, but I'm not sure how we want to position that relative to Grid 2.5. I'm note sure what "then entire gird" means.

What I've done here is port the existing documentation and label it "Grid 2.5". That way we can offer two different experiences on the gird (via a dialog presented at login time) and two different version of the documentation (via a version selector on the documentation site).

This is just one option, others include having separate documentation websites for 3.0 and 2.5, or replacing the existing documentation with the 3.0 documentation entirely.

**Comment by izahn** [comment]
2.5 is the grid as we've known it, 3.0 is the grid with what we've been calling the "technology preview". The main differences are that 3.0 offers improved application launchers and utilities, and includes a lot more software then 2.5.

**Comment by izahn** [comment]
The other key difference between the current stable release (2.5, from 2018) and the proposed 3.0 is a focus on simplicity and user-friendliness. 2.5 is presented as a mostly standard HPC environment; 3.0 goes to some lengths to be simpler and more accessible. This is evident in the more convenient and powerful application launchers, but also in the simpler but more comprehensive software environments, cluster and job monitoring utilities, and more succinct documentation.

**Comment by paul-dibello** [comment]
Ah.  OK, I would like to think of grid 2.5 as deprecated.  We will continue to support it on an ad-hoc basis, but generally speaking if it is not working for a user, they should upgrade.   The tech preview has been around for quite some time, seems stable, so asking folks to migrate shouldn't be that burdensome, in fact I suspect most will find it much easier to use.

**Comment by izahn** [comment]
Yes I agree. But "deprecated" is different from "replaced", so we need a way to present documentation for both. That's what I've tried to do here with the version selector drop-down menu. Totally open to other ways to doing this, that is just what I came up with as a first pass.

**Comment by izahn** [comment]
Done
