### ISSUE TITLE
Romove disclaimers and re-brand techpreview as grid 3.0

### ISSUE THREAD

**Issue by paul-dibello** [hbs-rcs/hbsgrid-docs#31]
I don't think we need the disclaimers as shown in the bold text below.

"cs_2022.01
After more than 6 months of hard work, the [HBS grid technology preview software environment](https://hbs-rcs.github.io/hbsgrid-docs/) version 2022.01 was released in January 2022! **This environment remains a technology preview and any and all use is at your own risk.**"

Also, throughout there should be some indication that if you need help you can email or call RCS.

**Comment by izahn** [comment]
Fixed in https://github.com/hbs-rcs/hbsgrid-docs/commit/68c7aa5034746d22f1cb3ce19b7c9bc03b207c34
