### ISSUE TITLE
Enter password to unlock pop-up

### ISSUE THREAD

**Issue by velmela** [hbs-rcs/hbsgrid-docs#35]
Whenever I open JupyterLab, I get a pop-up asking me to enter a password (see screenshot).
![Capture](https://user-images.githubusercontent.com/42443482/166475841-d2294dda-1330-46f2-8220-e7712fbfe0ee.JPG)

**Comment by izahn** [comment]
If you have forgotten your password you can try resetting it. I don't see much in the official Gnome documentation, but there are some instructions at https://www.pc-freak.net/blog/reset-gnome-forgotten-keyring-password/ and https://askubuntu.com/questions/65281/how-to-recover-reset-forgotten-gnome-keyring-password . Please give those a try and let us know how it goes!

**Comment by izahn** [comment]
See also https://github.com/hbs-rcs/hbsgrid-docs/discussions/39
