### ISSUE TITLE
DBeaver pop-up

### ISSUE THREAD

**Issue by velmela** [hbs-rcs/hbsgrid-docs#40]
When trying to navigate within DBeaver, I get the following pop-up (and didn't want to inadvertently install anything on the Grid):

![image](https://user-images.githubusercontent.com/42443482/168886729-39c088fd-aef4-4b5e-a024-eda9ab5b75c6.png)

Thank you!

**Comment by izahn** [comment]
Thank you for your caution and for checking before installing the driver @velmela ! In this case it is perfectly fine to download and install the driver. It will be stored in your home directly, i.e. in `~/.local/share/DBeaverData/drivers`

I added a note about this to the documentation in https://hbs-rcs.github.io/hbsgrid-docs/storage/#connecting-to-your-database

**Comment by velmela** [comment]
Awesome, thank you Ista!

Melissa Velez, PhD
Director, Data Services and Project Operations
Division of Research and Faculty Development

Harvard Business School
Baker Library | Bloomberg Center, B90
25 Harvard Way
Boston, MA 02163
T: 617-495-3292
