### ISSUE TITLE
Loading into grid gives a black screen

### ISSUE THREAD

**Issue by vaibhavholani** [hbs-rcs/hbsgrid-docs#47]
Hi, I have been trying to access the grid since morning but every time I open it I get a black screen and I am stuck there. I have attached a screenshot of the same
![Screenshot 2022-07-14 at 5 09 26 PM](https://user-images.githubusercontent.com/59990189/179086839-031cd875-a924-451a-bc1d-c5818ba0f331.png)
.

**Comment by izahn** [comment]
Thank you for reporting this! We are aware of intermittent login issues. It seems to be stable for me right now, can you try it again?

**Comment by vaibhavholani** [comment]
Hi, just tried it again. I still get a black screen.

**Comment by izahn** [comment]
The problem has been resolved. Please reopen if you still have any difficulties logging in.
