### ISSUE TITLE
Reading SAS File in JupyterLab on  Grid

### ISSUE THREAD

**Issue by hashzaman** [hbs-rcs/hbsgrid-docs#49]
Hi, 

I have a large SAS file that I am trying to read in JupyterLab on the Grid. I keep getting the attached error. I did pip install sas7bdat. Your thoughts would be helpful. 

Thanks
<img width="1338" alt="Screen Shot 2022-09-26 at 11 17 19 AM" src="https://user-images.githubusercontent.com/52306860/192315267-0afd08ca-2768-4cd1-8a1e-9b6fc3ca55e4.png">

**Comment by izahn** [comment]
The download from dropbox was incomplete, resulting in a corrupted .sas7bdat file.
